config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboard#index'
  get '/login', to: 'dashboard#index'

  get '/upload/download_all', to: 'upload#download_all', as: :download_all_upload
  resources :company
  resources :upload, exclude: [:new]
  resources :user, path: '/users/manage'
  post '/users/manage/revoke/:id', to: 'user#revoke_access', as: :revoke_user_access
  get '/upload/new/:company_id/:year', to: 'upload#new', as: :new_company_upload
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

  belongs_to :user
  has_many :uploads, dependent: :delete_all

  def self.search(search)
    if search
      self.where('lower(name) LIKE ?', "%#{search}%")
    else
      self.all
    end
  end

  def self.year_range(year_count)
    current_year = Date.current.year
    return (current_year - year_count .. current_year).to_a
  end

end

app/models/upload.rb
class Upload < ApplicationRecord

  mount_uploader :path, UploadUploader
  belongs_to :company
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :companies, dependent: :delete_all
  has_many :uploads, dependent: :delete_all

  def paginated_uploads(per_page, page)
    uploads.order(created_at: :desc).paginate(page: page, per_page: per_page)
  end

  def update_with_password(params, *options)
    current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = if params[:password].blank? || valid_password?(current_password)
      update_attributes(params, *options)
    else
      self.assign_attributes(params, *options)
      self.valid?
      self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
      false
    end

    clean_up_passwords
    result
  end

  def self.search(search)
    if search
      self.where('lower(name) LIKE ? OR lower(email) LIKE ?', "%#{search}%", "%#{search}%")
    else
      self.all
    end
  end

  def self.roles
    ['user', 'admin', 'super_admin']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :restrict_user

  protected

  def restrict_user
    if user_signed_in? && current_user.active != true
      sign_out
      flash[:alert] = 'User login not allowed'
      redirect_to new_user_session_path
    elsif current_user && current_user.role == 'user' && params[:controller] != 'devise/sessions'
      render 'user/no_permissions'
    end   
  end

end

app/controllers/company_controller.rb
class CompanyController < ApplicationController

  def new
    @company = Company.new
  end

  def create
    @company = current_user.companies.create(company_params)

    if @company.save
      redirect_to @company
    else
      flash[:error] = 'Can not save company'
      redirect_back fallback_location: new_company_path
    end 
  end

  def destroy

    if current_user.role != 'super_admin'
      flash[:error] = 'You don\'t have permissions to do this operation'
    else
      company = Company.find(params[:id])
      company.destroy
      flash[:info] = "Company #{company.name} successfully deleted"
    end

    redirect_to root_path

  end

  def show
    @company = Company.find(params[:id])
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
		if !user_signed_in?
			redirect_to new_user_session_path
		else 
      @companies = Company.search(params[:search]).order(created_at: :desc).paginate(page: params[:page], per_page: 20)
      @year_range = Company.year_range(5)
    end
	end

end

app/controllers/upload_controller.rb
module Zip
  class IOOutputStream < ZipOutputStream
    def initialize io
      super '-'
      @outputStream = io
    end

    def stream
      @outputStream
    end
  end
end

require "carrierwave"

class UploadController < ApplicationController

  attr_accessor :company_id

  def new
    @company = Company.find(params[:company_id])
    @year = params[:year]
    @upload = @company.uploads.new(year: @year)
  end

  def create
    @upload = Upload.create(upload_params)

    @upload.user = current_user

    if @upload.save
      redirect_to root_path
    else
      flash[:error] = 'Cannot upload'
      redirect_back fallback_location: root_path
    end 

  end

  def edit
  end

  def update
  end

  def destroy
    upload = Upload.find(params[:id])
      
    if upload.user == current_user || current_user.role == 'super_admin'
      upload.destroy!
    else
      flash[:error] = 'You don\'t have permissions to delete this upload'
    end

    redirect_back fallback_location: root_path
  end

  def show
    @upload = Upload.find(params[:id])
    file = @upload.path.file
    send_file file.class.method_defined?(:url) ? file.url : file.file
  end

  def download_all
    if current_user.role == 'super_admin'
       if !Upload.all.blank?

        file_name = "#{Date.current}_uploads.zip"
        t = Tempfile.new('mio-file-temp-2016-02-19 10:41:53 +0100')
        Zip::ZipOutputStream.open(t.path) do |z|
          Upload.all.each do |f|
          file = f.path.file
          z.put_next_entry(file.filename)
          z.print IO.read(file.class.method_defined?(:url) ? file.url : file.file)
          end
        end

        send_file t.path, :type => 'application/zip', :disposition => 'attachment', :filename => file_name
        t.close

        end
    else
      flash[:error] = 'You don\'t have permissions to delete this upload'
      redirect_back fallback_location: root_path
    end
  end

  private

  def upload_params
    params.require(:upload).permit(:path, :year, :company_id)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    active_param = params[:active] == 'canceled' ? false : true
    
    @target_users_name = active_param ? 'Active Users' : 'Suspended users'
    @user = User.new
    @users = User.where(active: active_param).where.not(id: current_user.id).search(params[:search]).order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  def new
  end

  def create
    user = User.create(user_params)

    if !user.save
      flash[:error] = 'Cannot create user'
    end

    redirect_back fallback_location: user_index_path
  end

  def show
    @user = User.find(params[:id])
    @user_uploads = @user.paginated_uploads(20, params[:page])
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete("password")
    end

    @user = User.find(params[:id])
    @user.update_attributes(user_params)
  end

  def edit
    @user = User.find(params[:id])
  end

  def revoke_access
    user = User.find(params[:id])
    user.active = params[:active] || false
    user.save
    redirect_back fallback_location: user_index_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :role)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/company/new.html.haml
.col-md-6.col-md-offset-3
  .well
    = render partial: 'layouts/partial/company_form', locals: {company: @company}

app/views/company/show.html.haml
%h2= @company.name
.text-muted
  Created by
  = @company.user.email
%hr
= link_to 'delete', @company, method: :delete
- if @company.uploads.any?
  .list-group
    - @company.uploads.each do |u|
      .list-group-item
        = link_to File.basename(u.path.url), u
        .text-right= link_to :delete, u, method: :delete
- else
  %h2.text-muted No uploads available

app/views/dashboard/index.html.haml
.text-right.page-header
  .row
    .col-md-offset-9.col-md-3
      = form_tag root_path, method: :get do
        .input-group
          = text_field_tag :search, params[:search], class: "form-control", placeholder: :search
          .input-group-btn
            = button_tag 'Search', class: 'btn btn-default'
            = link_to 'Clear', root_path, class: 'btn btn-danger'
%table.table.table-bordered
  %tr
    %th Company name
    - @year_range.each do |y|
      %th= y
  - @companies.each do |c|
    %tr
      %td= link_to c.name, c
      - @year_range.each do |y|
        - if (c.uploads.select {|u| u.year == y && c.id == u.company.id}).any?
          %td.success
            - upload = (c.uploads.find {|u| u.year == y && c.id == u.company.id})
            = link_to 'Download file', upload, target: :_blank
            - if current_user.role == 'super_admin' || current_user.id == upload.user.id
              &nbsp;
              = link_to 'x', upload, method: :delete, data: {confirm: 'Are you sure?'}
        - else  
          %td= link_to 'Upload file', new_company_upload_path(c, y)
- if current_user.role == 'super_admin'
  = link_to 'Download All', download_all_upload_path, target: :_blank
.pull-right= will_paginate @companies

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title UploadService
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/partial/main_menu'
    .container
      = render partial: 'layouts/partial/flash'
      = yield

app/views/layouts/partial/_company_form.html.haml
= form_for company, url: '/company' do |f|
  %div
    = f.label :name
    %br
    = f.text_field :name, :autofocus => true, class: 'form-control'
  %br
  %div= f.submit "Save company", class: 'btn btn-success', "data-loading-text" => "Loading..."

app/views/layouts/partial/_flash.html.haml
- if !flash.empty?
  .alert.alert-info
    - flash.each do |type, msg|
      = msg

app/views/layouts/partial/_main_menu.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} Database
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.active
          - if !user_signed_in?
            %li= link_to 'Login', new_user_session_path
          - else
            - if current_user.role === 'super_admin'
              %li= link_to 'Add new company', new_company_path
              %li= link_to 'Users', user_index_path
            %li= link_to current_user.email, edit_user_registration_path
            %li= link_to 'Logout', destroy_user_session_path, method: 'delete'

app/views/upload/new.html.haml
%h3 Upload for "#{@upload.company.name}" company
%h2.text-muted= @upload.year
= form_for @upload, url: '/upload' do |f|
  = f.hidden_field :company_id, value: @company.id
  = f.hidden_field :year, value: @year
  = f.label :path
  = f.file_field :path
  = button_tag(type: "submit", class: "orange-d2 pull-left") do
    Save

app/views/user/edit.html.haml
= form_for @user do |f|
  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, class: 'form-control'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password
    = f.text_field :password, class: 'form-control'
    .text-muted Leave blank if you don't want change password
  .form-group
    = f.label :role
    = f.select :role, options_for_select(@user.class.roles, @user.role), {}, {class: 'form-control'}
  = f.submit "Save user", class: 'btn btn-success', "data-loading-text" => "Loading..."

app/views/user/index.html.haml
.page-header Add new user

.row
  = form_for @user, url: '/users/manage' do |f|
    .col-sm-2
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .col-sm-2
      = f.label :email
      = f.email_field :email, class: 'form-control'
    .col-sm-2
      = f.label :password
      = f.password_field :password, class: 'form-control'
    .col-sm-2
      = f.label :role
      = f.select :role, options_for_select(@user.class.roles), {}, {class: 'form-control'}
    .col-sm-2
      %br
      = button_tag 'Add', class: 'btn btn-primary'


.col-md-offset-9.col-md-3
  = form_tag user_index_path, method: :get do
    .input-group
      = text_field_tag :search, params[:search], class: "form-control", placeholder: :search
      = hidden_field_tag :active, params[:active]
      .input-group-btn
        = button_tag 'Search', class: 'btn btn-default'
        = link_to 'Clear', user_index_path, class: 'btn btn-danger'
%hr

.panel.panel-info
  .panel-heading
    = @target_users_name
    .btn-group.pull-right
      = link_to 'Active users', user_index_path
      = link_to 'Suspended users', user_index_path(active: :canceled)
  - if @users.any?
    %table.table
      - @users.each do |u|
        %tr
          %td= link_to u.name, u
          %td= u.email
          %td= u.role.capitalize
          %td
            .form-group
              = link_to 'Edit', edit_user_path(u), class: 'btn btn-info'
              - if u.active
                = link_to 'Revoke access', revoke_user_access_path(u), class: 'btn btn-warning', method: :posts
              - else
                = link_to 'Grant access', revoke_user_access_path(u, active: true), class: 'btn btn-warning', method: :posts
  - else
    .panel-body
      %h4.text-muted= "There are no #{@target_users_name} available in database"
  .panel-footer
    .text-right= will_paginate @users

app/views/user/no_permissions.html.haml
%h4 You don't have any permissions on this website. Please contact administrator

app/views/user/show.html.haml
%h3= @user.name
%h4.text-muted= @user.email

.panel.panel-info
  .panel-heading Uploaded files
  - if @user.uploads.any?
    %table.table
      %tr
        %th Company
        %th Year
        %th Date
        %th Download
      - @user_uploads.each do |upload|
        %tr
          %td= upload.company.name
          %td= upload.year
          %td= upload.created_at.strftime("%m/%d/%Y at %I:%M%p")
          %td= link_to 'Download', upload, target: :_blank
    
  - else
    .panel-body
      %h3.text-muted User has no uploaded files yet
  .panel-footer
    .text-right= will_paginate @user_uploads